// telc B1 스프린트 — 배치 1: A2 핵심 (A1은 건너뜀)
// vocab: de(표제어), pl(복수), gr(불규칙 3인칭·과거분사 등 문법정보), ko(뜻), ex(예문), exKo(예문 뜻)
const VOCAB = [
  // ---- 분리동사 · 일상 동사 (Perfekt 정보 포함) ----
  {id:"v001", de:"anfangen", gr:"er fängt an · hat angefangen", ko:"시작하다", ex:"Der Kurs fängt um neun an.", exKo:"수업은 9시에 시작해요."},
  {id:"v002", de:"aufhören", gr:"hat aufgehört", ko:"그만두다, 끝나다", ex:"Hör bitte auf!", exKo:"제발 그만해!"},
  {id:"v003", de:"anrufen", gr:"hat angerufen", ko:"전화하다", ex:"Ich rufe dich morgen an.", exKo:"내일 전화할게."},
  {id:"v004", de:"abholen", gr:"hat abgeholt", ko:"데리러 가다, 찾아오다", ex:"Ich hole dich vom Bahnhof ab.", exKo:"기차역으로 데리러 갈게."},
  {id:"v005", de:"einkaufen", gr:"hat eingekauft", ko:"장을 보다", ex:"Samstags kaufen wir im Supermarkt ein.", exKo:"토요일마다 우리는 슈퍼에서 장을 봐요."},
  {id:"v006", de:"aufstehen", gr:"ist aufgestanden", ko:"일어나다", ex:"Ich stehe jeden Tag um sechs auf.", exKo:"나는 매일 6시에 일어나요."},
  {id:"v007", de:"fernsehen", gr:"er sieht fern · hat ferngesehen", ko:"텔레비전을 보다", ex:"Abends sehe ich oft fern.", exKo:"저녁에 나는 자주 TV를 봐요."},
  {id:"v008", de:"mitbringen", gr:"hat mitgebracht", ko:"가져오다", ex:"Was soll ich zur Party mitbringen?", exKo:"파티에 뭘 가져갈까?"},
  {id:"v009", de:"einladen", gr:"er lädt ein · hat eingeladen", ko:"초대하다", ex:"Ich lade dich zum Essen ein.", exKo:"내가 식사에 초대할게(밥 살게)."},
  {id:"v010", de:"ankommen", gr:"ist angekommen", ko:"도착하다", ex:"Der Zug ist pünktlich angekommen.", exKo:"기차가 제시간에 도착했어요."},
  {id:"v011", de:"abfahren", gr:"er fährt ab · ist abgefahren", ko:"출발하다", ex:"Der Bus fährt gleich ab.", exKo:"버스가 곧 출발해요."},
  {id:"v012", de:"einsteigen", gr:"ist eingestiegen", ko:"(탈것에) 타다", ex:"Bitte einsteigen!", exKo:"탑승해 주세요!"},
  {id:"v013", de:"aussteigen", gr:"ist ausgestiegen", ko:"내리다", ex:"Wir steigen an der nächsten Haltestelle aus.", exKo:"우리는 다음 정류장에서 내려요."},
  {id:"v014", de:"umsteigen", gr:"ist umgestiegen", ko:"갈아타다", ex:"Sie müssen in Frankfurt umsteigen.", exKo:"프랑크푸르트에서 갈아타셔야 해요."},
  {id:"v015", de:"bekommen", gr:"hat bekommen", ko:"받다", ex:"Ich habe deine Nachricht bekommen.", exKo:"네 메시지 받았어."},
  {id:"v016", de:"bezahlen", gr:"hat bezahlt", ko:"지불하다", ex:"Kann ich mit Karte bezahlen?", exKo:"카드로 계산해도 되나요?"},
  {id:"v017", de:"bestellen", gr:"hat bestellt", ko:"주문하다", ex:"Ich habe schon bestellt.", exKo:"저는 이미 주문했어요."},
  {id:"v018", de:"erklären", gr:"hat erklärt", ko:"설명하다", ex:"Können Sie das bitte erklären?", exKo:"그걸 설명해 주시겠어요?"},
  {id:"v019", de:"erzählen", gr:"hat erzählt", ko:"이야기해 주다", ex:"Erzähl mal!", exKo:"얘기해 봐!"},
  {id:"v020", de:"vergessen", gr:"er vergisst · hat vergessen", ko:"잊다", ex:"Ich habe den Termin vergessen.", exKo:"나는 그 약속을 잊어버렸어요."},
  {id:"v021", de:"verlieren", gr:"hat verloren", ko:"잃어버리다", ex:"Ich habe meinen Schlüssel verloren.", exKo:"나는 열쇠를 잃어버렸어요."},
  {id:"v022", de:"versuchen", gr:"hat versucht", ko:"시도하다", ex:"Ich versuche es noch einmal.", exKo:"한 번 더 해볼게요."},
  {id:"v023", de:"passieren", gr:"ist passiert", ko:"(일이) 일어나다", ex:"Was ist passiert?", exKo:"무슨 일이 있었어요?"},
  {id:"v024", de:"gehören", gr:"+ Dativ · hat gehört", ko:"~의 것이다", ex:"Das Handy gehört mir.", exKo:"그 휴대폰은 내 거예요."},
  {id:"v025", de:"gefallen", gr:"+ Dativ · er gefällt · hat gefallen", ko:"마음에 들다", ex:"Frankfurt gefällt mir gut.", exKo:"프랑크푸르트가 마음에 들어요."},
  {id:"v026", de:"schmecken", gr:"hat geschmeckt", ko:"맛이 ~하다", ex:"Hat es geschmeckt?", exKo:"맛있었어요?"},
  {id:"v027", de:"wehtun", gr:"hat wehgetan", ko:"아프다", ex:"Mein Rücken tut weh.", exKo:"허리가 아파요."},
  {id:"v028", de:"sich freuen", gr:"auf + Akk · hat sich gefreut", ko:"기뻐하다, 기대하다", ex:"Ich freue mich auf das Wochenende.", exKo:"주말이 기대돼요."},
  {id:"v029", de:"sich treffen", gr:"er trifft sich · hat sich getroffen", ko:"만나다", ex:"Wir treffen uns um sieben.", exKo:"우리는 7시에 만나요."},
  {id:"v030", de:"sich fühlen", gr:"hat sich gefühlt", ko:"(몸·기분을) 느끼다", ex:"Ich fühle mich heute besser.", exKo:"오늘은 몸이 좀 나아요."},
  {id:"v031", de:"umziehen", gr:"ist umgezogen", ko:"이사하다", ex:"Wir sind nach Frankfurt umgezogen.", exKo:"우리는 프랑크푸르트로 이사했어요."},
  {id:"v032", de:"mieten", gr:"hat gemietet", ko:"세내다, 빌리다", ex:"Wir haben eine Wohnung gemietet.", exKo:"우리는 집을 하나 빌렸어요."},
  {id:"v033", de:"reparieren", gr:"hat repariert", ko:"수리하다", ex:"Er repariert gerade das Auto.", exKo:"그는 지금 차를 수리하고 있어요."},
  {id:"v034", de:"schicken", gr:"hat geschickt", ko:"보내다", ex:"Ich schicke dir die Adresse.", exKo:"주소 보내줄게."},
  {id:"v035", de:"warten", gr:"auf + Akk · hat gewartet", ko:"기다리다", ex:"Wir warten auf den Bus.", exKo:"우리는 버스를 기다리고 있어요."},
  // ---- 명사: 교통 · 관공서 · 집 · 직장 · 건강 ----
  {id:"v036", de:"der Flughafen", pl:"Flughäfen", ko:"공항", ex:"Der Flughafen ist weit weg.", exKo:"공항은 멀리 있어요."},
  {id:"v037", de:"die Haltestelle", pl:"Haltestellen", ko:"정류장", ex:"Wo ist die nächste Haltestelle?", exKo:"가장 가까운 정류장이 어디예요?"},
  {id:"v038", de:"die Verspätung", pl:"Verspätungen", ko:"연착, 지연", ex:"Der Zug hat zwanzig Minuten Verspätung.", exKo:"기차가 20분 연착이에요."},
  {id:"v039", de:"die Fahrkarte", pl:"Fahrkarten", ko:"승차권", ex:"Ich habe die Fahrkarte schon gekauft.", exKo:"표는 이미 샀어요."},
  {id:"v040", de:"der Führerschein", pl:"Führerscheine", ko:"운전면허증", ex:"Er macht gerade den Führerschein.", exKo:"그는 지금 운전면허를 따고 있어요."},
  {id:"v041", de:"der Ausweis", pl:"Ausweise", ko:"신분증", ex:"Ihren Ausweis, bitte.", exKo:"신분증 부탁드립니다."},
  {id:"v042", de:"die Anmeldung", pl:"Anmeldungen", ko:"등록, 신고", ex:"Die Anmeldung ist kostenlos.", exKo:"등록은 무료예요."},
  {id:"v043", de:"das Formular", pl:"Formulare", ko:"서식, 양식", ex:"Bitte füllen Sie das Formular aus.", exKo:"이 서식을 작성해 주세요."},
  {id:"v044", de:"die Unterschrift", pl:"Unterschriften", ko:"서명", ex:"Ich brauche noch Ihre Unterschrift.", exKo:"서명이 아직 필요해요."},
  {id:"v045", de:"der Vertrag", pl:"Verträge", ko:"계약(서)", ex:"Ich habe den Vertrag unterschrieben.", exKo:"나는 계약서에 서명했어요."},
  {id:"v046", de:"die Miete", pl:"Mieten", ko:"월세", ex:"Die Miete ist sehr hoch.", exKo:"월세가 아주 비싸요."},
  {id:"v047", de:"der Nachbar", pl:"Nachbarn", ko:"이웃", ex:"Unsere Nachbarn sind sehr freundlich.", exKo:"우리 이웃들은 아주 친절해요."},
  {id:"v048", de:"der Schlüssel", pl:"Schlüssel", ko:"열쇠", ex:"Wo ist mein Schlüssel?", exKo:"내 열쇠 어디 있지?"},
  {id:"v049", de:"die Rechnung", pl:"Rechnungen", ko:"계산서, 청구서", ex:"Die Rechnung, bitte!", exKo:"계산서 주세요!"},
  {id:"v050", de:"das Angebot", pl:"Angebote", ko:"할인 상품, 제안", ex:"Das ist ein gutes Angebot.", exKo:"좋은 조건(할인)이네요."},
  {id:"v051", de:"der Kunde", pl:"Kunden", ko:"고객", ex:"Der Kunde ist König.", exKo:"고객은 왕이다."},
  {id:"v052", de:"die Gesundheit", ko:"건강", ex:"Rauchen ist schlecht für die Gesundheit.", exKo:"흡연은 건강에 나빠요."},
  {id:"v053", de:"das Fieber", ko:"열", ex:"Das Kind hat hohes Fieber.", exKo:"아이가 열이 높아요."},
  {id:"v054", de:"die Erkältung", pl:"Erkältungen", ko:"감기", ex:"Ich habe eine Erkältung.", exKo:"나 감기 걸렸어요."},
  {id:"v055", de:"der Schmerz", pl:"Schmerzen", ko:"통증", ex:"Ich habe starke Schmerzen.", exKo:"통증이 심해요."},
  {id:"v056", de:"die Apotheke", pl:"Apotheken", ko:"약국", ex:"Die Apotheke ist gleich um die Ecke.", exKo:"약국은 바로 모퉁이에 있어요."},
  {id:"v057", de:"das Medikament", pl:"Medikamente", ko:"약", ex:"Nehmen Sie das Medikament dreimal täglich.", exKo:"이 약을 하루 세 번 드세요."},
  {id:"v058", de:"das Rezept", pl:"Rezepte", ko:"처방전; 요리법", ex:"Dieses Medikament gibt es nur auf Rezept.", exKo:"이 약은 처방전이 있어야만 살 수 있어요."},
  {id:"v059", de:"die Versicherung", pl:"Versicherungen", ko:"보험", ex:"Die Versicherung bezahlt das.", exKo:"그건 보험이 지불해요."},
  {id:"v060", de:"die Prüfung", pl:"Prüfungen", ko:"시험", ex:"Er hat die Prüfung bestanden.", exKo:"그는 시험에 합격했어요."},
  {id:"v061", de:"die Ausbildung", pl:"Ausbildungen", ko:"직업교육", ex:"Sie macht eine Ausbildung.", exKo:"그녀는 직업교육을 받고 있어요."},
  {id:"v062", de:"das Gehalt", pl:"Gehälter", ko:"월급", ex:"Das Gehalt ist nicht schlecht.", exKo:"월급이 나쁘지 않아요."},
  {id:"v063", de:"die Stelle", pl:"Stellen", ko:"일자리", ex:"Er sucht eine neue Stelle.", exKo:"그는 새 일자리를 찾고 있어요."},
  {id:"v064", de:"der Chef", pl:"Chefs", ko:"상사, 사장", ex:"Mein Chef ist heute nicht da.", exKo:"우리 사장님은 오늘 안 계세요."},
  {id:"v065", de:"der Kollege", pl:"Kollegen", ko:"동료", ex:"Meine Kollegen sind nett.", exKo:"내 동료들은 친절해요."},
  {id:"v066", de:"die Besprechung", pl:"Besprechungen", ko:"회의", ex:"Die Besprechung dauert eine Stunde.", exKo:"회의는 한 시간 걸려요."},
  {id:"v067", de:"der Feiertag", pl:"Feiertage", ko:"공휴일", ex:"Morgen ist ein Feiertag.", exKo:"내일은 공휴일이에요."},
  {id:"v068", de:"das Wetter", ko:"날씨", ex:"Das Wetter wird morgen besser.", exKo:"날씨가 내일 나아질 거예요."},
  {id:"v069", de:"der Regen", ko:"비", ex:"Bei Regen bleiben wir zu Hause.", exKo:"비가 오면 우리는 집에 있어요."},
  {id:"v070", de:"der Schnee", ko:"눈(雪)", ex:"Im Winter gibt es hier viel Schnee.", exKo:"겨울에 여기는 눈이 많이 와요."},
  {id:"v071", de:"die Umwelt", ko:"환경", ex:"Das ist gut für die Umwelt.", exKo:"그건 환경에 좋아요."},
  {id:"v072", de:"der Müll", ko:"쓰레기", ex:"Bitte trennen Sie den Müll.", exKo:"쓰레기를 분리해 주세요."},
  {id:"v073", de:"die Heizung", pl:"Heizungen", ko:"난방", ex:"Die Heizung funktioniert nicht.", exKo:"난방이 안 돼요."},
  {id:"v074", de:"der Aufzug", pl:"Aufzüge", ko:"엘리베이터", ex:"Der Aufzug ist kaputt.", exKo:"엘리베이터가 고장 났어요."},
  {id:"v075", de:"das Erdgeschoss", pl:"Erdgeschosse", ko:"1층(지상층)", ex:"Wir wohnen im Erdgeschoss.", exKo:"우리는 1층에 살아요."},
  {id:"v076", de:"der Keller", pl:"Keller", ko:"지하실", ex:"Die Fahrräder stehen im Keller.", exKo:"자전거들은 지하실에 있어요."},
  {id:"v077", de:"die Nachricht", pl:"Nachrichten", ko:"소식, 메시지", ex:"Ich habe eine gute Nachricht.", exKo:"좋은 소식이 있어요."},
  {id:"v078", de:"das Gespräch", pl:"Gespräche", ko:"대화", ex:"Wir hatten ein langes Gespräch.", exKo:"우리는 긴 대화를 나눴어요."},
  {id:"v079", de:"die Einladung", pl:"Einladungen", ko:"초대(장)", ex:"Danke für die Einladung!", exKo:"초대해 줘서 고마워요!"},
  {id:"v080", de:"das Geschenk", pl:"Geschenke", ko:"선물", ex:"Das Geschenk gefällt ihr bestimmt.", exKo:"그 선물은 분명 그녀 마음에 들 거예요."},
  // ---- 형용사 ----
  {id:"v081", de:"wichtig", ko:"중요한", ex:"Das ist mir sehr wichtig.", exKo:"그건 나에게 아주 중요해요."},
  {id:"v082", de:"möglich", ko:"가능한", ex:"Ist das möglich?", exKo:"그게 가능해요?"},
  {id:"v083", de:"günstig", ko:"저렴한, 유리한", ex:"Das Hotel war ziemlich günstig.", exKo:"그 호텔은 꽤 저렴했어요."},
  {id:"v084", de:"kostenlos", ko:"무료의", ex:"Der Eintritt ist kostenlos.", exKo:"입장은 무료예요."},
  {id:"v085", de:"pünktlich", ko:"시간을 지키는", ex:"Bitte sei pünktlich!", exKo:"제시간에 와!"},
  {id:"v086", de:"zufrieden", ko:"만족한", ex:"Ich bin mit der Arbeit zufrieden.", exKo:"나는 그 일에 만족해요."},
  {id:"v087", de:"traurig", ko:"슬픈", ex:"Warum bist du so traurig?", exKo:"왜 그렇게 슬퍼해?"},
  {id:"v088", de:"glücklich", ko:"행복한", ex:"Sie sieht glücklich aus.", exKo:"그녀는 행복해 보여요."},
  {id:"v089", de:"laut", ko:"시끄러운", ex:"Die Musik ist zu laut.", exKo:"음악이 너무 시끄러워요."},
  {id:"v090", de:"leise", ko:"조용한", ex:"Sprich bitte leise!", exKo:"조용히 말해 줘!"},
  {id:"v091", de:"sauber", ko:"깨끗한", ex:"Die Küche ist jetzt sauber.", exKo:"부엌이 이제 깨끗해요."},
  {id:"v092", de:"schmutzig", ko:"더러운", ex:"Meine Schuhe sind schmutzig.", exKo:"내 신발이 더러워요."},
  {id:"v093", de:"schwierig", ko:"어려운", ex:"Die Frage ist schwierig.", exKo:"그 질문은 어려워요."},
  {id:"v094", de:"einfach", ko:"쉬운, 간단한", ex:"Das ist ganz einfach.", exKo:"그건 아주 간단해요."},
  {id:"v095", de:"fertig", ko:"다 된, 끝난", ex:"Bist du fertig?", exKo:"너 다 했어?"},
  {id:"v096", de:"kaputt", ko:"고장 난", ex:"Die Waschmaschine ist kaputt.", exKo:"세탁기가 고장 났어요."},
  {id:"v097", de:"frei", ko:"비어 있는, 자유로운", ex:"Ist dieser Platz noch frei?", exKo:"이 자리 비어 있나요?"},
  {id:"v098", de:"besetzt", ko:"사용 중인, 차 있는", ex:"Die Toilette ist besetzt.", exKo:"화장실이 사용 중이에요."},
  {id:"v099", de:"anstrengend", ko:"힘든, 고된", ex:"Der Tag war sehr anstrengend.", exKo:"오늘 하루는 아주 힘들었어요."},
  {id:"v100", de:"spannend", ko:"흥미진진한", ex:"Der Film war spannend.", exKo:"그 영화는 흥미진진했어요."},
  {id:"v101", de:"langweilig", ko:"지루한", ex:"Die Vorlesung war langweilig.", exKo:"그 강의는 지루했어요."},
  {id:"v102", de:"gefährlich", ko:"위험한", ex:"Das ist zu gefährlich.", exKo:"그건 너무 위험해요."},
  {id:"v103", de:"bequem", ko:"편안한", ex:"Der Sessel ist sehr bequem.", exKo:"그 안락의자는 아주 편해요."},
  {id:"v104", de:"eigentlich", ko:"사실은, 원래", ex:"Eigentlich wollte ich früher gehen.", exKo:"사실 나는 더 일찍 가려고 했어요."},
  // ---- 접속사 · 부사 (A2 문법 핵심) ----
  {id:"v105", de:"weil", gr:"부문장: 동사 맨 끝", ko:"~때문에", ex:"Ich bleibe zu Hause, weil ich krank bin.", exKo:"나는 아파서 집에 있어요."},
  {id:"v106", de:"dass", gr:"부문장: 동사 맨 끝", ko:"~라는 것", ex:"Ich glaube, dass er recht hat.", exKo:"나는 그가 옳다고 생각해요."},
  {id:"v107", de:"wenn", gr:"부문장: 동사 맨 끝", ko:"~할 때, ~라면", ex:"Wenn es regnet, nehme ich den Bus.", exKo:"비가 오면 나는 버스를 타요."},
  {id:"v108", de:"deshalb", gr:"뒤 문장 도치", ko:"그래서", ex:"Ich war müde, deshalb bin ich früh ins Bett gegangen.", exKo:"나는 피곤해서 일찍 잤어요."},
  {id:"v109", de:"trotzdem", gr:"뒤 문장 도치", ko:"그럼에도 불구하고", ex:"Es regnet, trotzdem gehen wir spazieren.", exKo:"비가 오지만 그래도 우리는 산책해요."},
  {id:"v110", de:"zuerst", ko:"우선, 먼저", ex:"Zuerst frühstücke ich.", exKo:"먼저 나는 아침을 먹어요."},
  {id:"v111", de:"danach", ko:"그 후에", ex:"Danach gehe ich zur Arbeit.", exKo:"그 후에 나는 일하러 가요."},
  {id:"v112", de:"plötzlich", ko:"갑자기", ex:"Plötzlich hat es geregnet.", exKo:"갑자기 비가 왔어요."},
  {id:"v113", de:"schon", ko:"이미, 벌써", ex:"Ich bin schon fertig.", exKo:"나 벌써 다 했어."},
  {id:"v114", de:"noch", ko:"아직, 더", ex:"Ich brauche noch zehn Minuten.", exKo:"10분 더 필요해요."},
  {id:"v115", de:"erst", ko:"겨우, ~이 되어서야", ex:"Er kommt erst um zehn.", exKo:"그는 10시나 되어야 와요."},
  {id:"v116", de:"bald", ko:"곧", ex:"Bis bald!", exKo:"곧 봐요!"},
  {id:"v117", de:"früher", ko:"예전에", ex:"Früher habe ich in Seoul gewohnt.", exKo:"예전에 나는 서울에 살았어요."},
  {id:"v118", de:"letzte Woche", ko:"지난주", ex:"Letzte Woche war ich krank.", exKo:"지난주에 나는 아팠어요."},
  {id:"v119", de:"nächstes Jahr", ko:"내년", ex:"Nächstes Jahr machen wir Urlaub in Korea.", exKo:"내년에 우리는 한국에서 휴가를 보내요."},
  {id:"v120", de:"zum Beispiel", ko:"예를 들면", ex:"Ich mag Obst, zum Beispiel Äpfel.", exKo:"나는 과일을 좋아해요, 예를 들면 사과요."},

  // ---- 배치 2: A2 완성 + B1 진입 (v121~v320) ----
  {id:"v121", de:"bringen", gr:"hat gebracht", ko:"가져다주다", ex:"Bringst du mir ein Glas Wasser?", exKo:"물 한 잔 갖다줄래?"},
  {id:"v122", de:"holen", gr:"hat geholt", ko:"가지러 가다", ex:"Ich hole schnell meine Jacke.", exKo:"재킷 금방 가져올게."},
  {id:"v123", de:"stellen", gr:"hat gestellt", ko:"세워 놓다", ex:"Stell die Vase auf den Tisch.", exKo:"꽃병을 탁자 위에 세워 놔."},
  {id:"v124", de:"legen", gr:"hat gelegt", ko:"눕혀 놓다", ex:"Leg das Buch auf den Schreibtisch.", exKo:"책을 책상 위에 놓아 줘."},
  {id:"v125", de:"hängen", gr:"hat gehängt", ko:"걸다", ex:"Ich hänge das Bild an die Wand.", exKo:"그림을 벽에 걸어요."},
  {id:"v126", de:"öffnen", gr:"hat geöffnet", ko:"열다", ex:"Können Sie bitte das Fenster öffnen?", exKo:"창문 좀 열어 주시겠어요?"},
  {id:"v127", de:"schließen", gr:"hat geschlossen", ko:"닫다", ex:"Der Laden schließt um acht Uhr.", exKo:"가게는 8시에 닫아요."},
  {id:"v128", de:"beginnen", gr:"hat begonnen", ko:"시작되다", ex:"Der Film beginnt gleich.", exKo:"영화가 곧 시작해요."},
  {id:"v129", de:"enden", gr:"hat geendet", ko:"끝나다", ex:"Der Kurs endet im Juli.", exKo:"수업은 7월에 끝나요."},
  {id:"v130", de:"dauern", gr:"hat gedauert", ko:"(시간이) 걸리다", ex:"Die Fahrt dauert zwei Stunden.", exKo:"가는 데 두 시간 걸려요."},
  {id:"v131", de:"benutzen", gr:"hat benutzt", ko:"사용하다", ex:"Darf ich kurz dein Handy benutzen?", exKo:"네 휴대폰 잠깐 써도 돼?"},
  {id:"v132", de:"verwenden", gr:"hat verwendet", ko:"사용하다, 쓰다", ex:"Ich verwende viel Olivenöl.", exKo:"나는 올리브유를 많이 써요."},
  {id:"v133", de:"funktionieren", gr:"hat funktioniert", ko:"작동하다", ex:"Der Drucker funktioniert wieder.", exKo:"프린터가 다시 작동해요."},
  {id:"v134", de:"klingeln", gr:"hat geklingelt", ko:"벨이 울리다", ex:"Das Telefon klingelt.", exKo:"전화벨이 울려요."},
  {id:"v135", de:"anmachen", gr:"hat angemacht", ko:"켜다", ex:"Mach bitte das Licht an.", exKo:"불 좀 켜 줘."},
  {id:"v136", de:"ausmachen", gr:"hat ausgemacht", ko:"끄다", ex:"Mach den Fernseher aus.", exKo:"TV 좀 꺼."},
  {id:"v137", de:"abgeben", gr:"er gibt ab · hat abgegeben", ko:"제출하다", ex:"Ich muss die Hausaufgabe morgen abgeben.", exKo:"숙제를 내일 제출해야 해요."},
  {id:"v138", de:"ausfüllen", gr:"hat ausgefüllt", ko:"(서식을) 작성하다", ex:"Füllen Sie bitte dieses Formular aus.", exKo:"이 서식을 작성해 주세요."},
  {id:"v139", de:"unterschreiben", gr:"hat unterschrieben", ko:"서명하다", ex:"Unterschreiben Sie bitte hier.", exKo:"여기에 서명해 주세요."},
  {id:"v140", de:"beantragen", gr:"hat beantragt", ko:"신청하다", ex:"Ich möchte einen neuen Pass beantragen.", exKo:"새 여권을 신청하고 싶어요."},
  {id:"v141", de:"verdienen", gr:"hat verdient", ko:"(돈을) 벌다", ex:"Er verdient ganz gut.", exKo:"그는 꽤 잘 벌어요."},
  {id:"v142", de:"ausgeben", gr:"er gibt aus · hat ausgegeben", ko:"(돈을) 쓰다", ex:"Ich gebe zu viel Geld für Essen aus.", exKo:"나는 먹는 데 돈을 너무 많이 써요."},
  {id:"v143", de:"sparen", gr:"hat gespart", ko:"저축하다, 아끼다", ex:"Wir sparen für den Urlaub.", exKo:"우리는 휴가를 위해 저축해요."},
  {id:"v144", de:"leihen", gr:"hat geliehen", ko:"빌려주다", ex:"Kannst du mir zehn Euro leihen?", exKo:"10유로만 빌려줄 수 있어?"},
  {id:"v145", de:"zurückgeben", gr:"er gibt zurück · hat zurückgegeben", ko:"돌려주다", ex:"Ich gebe dir das Buch morgen zurück.", exKo:"책은 내일 돌려줄게."},
  {id:"v146", de:"anbieten", gr:"hat angeboten", ko:"제공하다, 제안하다", ex:"Die Firma bietet gute Stellen an.", exKo:"그 회사는 좋은 일자리를 제공해요."},
  {id:"v147", de:"empfehlen", gr:"er empfiehlt · hat empfohlen", ko:"추천하다", ex:"Können Sie ein Restaurant empfehlen?", exKo:"식당 하나 추천해 주시겠어요?"},
  {id:"v148", de:"entscheiden", gr:"hat entschieden", ko:"결정하다", ex:"Ich habe mich noch nicht entschieden.", exKo:"아직 결정을 못 했어요."},
  {id:"v149", de:"wählen", gr:"hat gewählt", ko:"고르다, 선택하다", ex:"Wählen Sie bitte ein Menü.", exKo:"메뉴를 골라 주세요."},
  {id:"v150", de:"vergleichen", gr:"hat verglichen", ko:"비교하다", ex:"Ich vergleiche zuerst die Preise.", exKo:"먼저 가격을 비교해요."},
  {id:"v151", de:"prüfen", gr:"hat geprüft", ko:"확인하다, 점검하다", ex:"Bitte prüfen Sie Ihre Daten.", exKo:"정보를 확인해 주세요."},
  {id:"v152", de:"verbessern", gr:"hat verbessert", ko:"개선하다", ex:"Ich möchte mein Deutsch verbessern.", exKo:"독일어 실력을 늘리고 싶어요."},
  {id:"v153", de:"üben", gr:"hat geübt", ko:"연습하다", ex:"Wir üben jeden Tag zusammen.", exKo:"우리는 매일 함께 연습해요."},
  {id:"v154", de:"wiederholen", gr:"hat wiederholt", ko:"반복하다", ex:"Können Sie das bitte wiederholen?", exKo:"다시 한번 말씀해 주시겠어요?"},
  {id:"v155", de:"übersetzen", gr:"hat übersetzt", ko:"번역하다", ex:"Kannst du das für mich übersetzen?", exKo:"이거 번역해 줄 수 있어?"},
  {id:"v156", de:"bedeuten", gr:"hat bedeutet", ko:"의미하다", ex:"Was bedeutet dieses Wort?", exKo:"이 단어는 무슨 뜻이에요?"},
  {id:"v157", de:"erlauben", gr:"hat erlaubt", ko:"허락하다", ex:"Meine Vermieterin erlaubt keine Haustiere.", exKo:"집주인이 반려동물을 허락하지 않아요."},
  {id:"v158", de:"verbieten", gr:"hat verboten", ko:"금지하다", ex:"Rauchen ist hier verboten.", exKo:"여기는 금연이에요."},
  {id:"v159", de:"stören", gr:"hat gestört", ko:"방해하다", ex:"Störe ich dich gerade?", exKo:"지금 방해되니?"},
  {id:"v160", de:"sich beeilen", gr:"hat sich beeilt", ko:"서두르다", ex:"Beeil dich, der Zug fährt gleich!", exKo:"서둘러, 기차 곧 출발해!"},
  {id:"v161", de:"sich ausruhen", gr:"hat sich ausgeruht", ko:"쉬다", ex:"Am Sonntag ruhe ich mich aus.", exKo:"일요일엔 푹 쉬어요."},
  {id:"v162", de:"sich kümmern", gr:"um + Akk · hat sich gekümmert", ko:"돌보다, 신경 쓰다", ex:"Sie kümmert sich um die Kinder.", exKo:"그녀는 아이들을 돌봐요."},
  {id:"v163", de:"sich ärgern", gr:"über + Akk · hat sich geärgert", ko:"화가 나다", ex:"Ich ärgere mich über den Lärm.", exKo:"소음 때문에 화가 나요."},
  {id:"v164", de:"sich beschweren", gr:"hat sich beschwert", ko:"항의하다", ex:"Ich möchte mich beschweren.", exKo:"항의하고 싶은데요."},
  {id:"v165", de:"sich anmelden", gr:"hat sich angemeldet", ko:"등록하다", ex:"Ich melde mich für den B1-Kurs an.", exKo:"B1 수업에 등록해요."},
  {id:"v166", de:"sich bewerben", gr:"er bewirbt sich · hat sich beworben", ko:"지원하다", ex:"Er bewirbt sich um die Stelle.", exKo:"그는 그 자리에 지원해요."},
  {id:"v167", de:"kündigen", gr:"hat gekündigt", ko:"해지하다, 그만두다", ex:"Sie hat ihren Job gekündigt.", exKo:"그녀는 일을 그만뒀어요."},
  {id:"v168", de:"einziehen", gr:"ist eingezogen", ko:"입주하다", ex:"Wir ziehen nächste Woche ein.", exKo:"우리는 다음 주에 입주해요."},
  {id:"v169", de:"ausziehen", gr:"ist ausgezogen", ko:"이사 나가다", ex:"Er ist mit 20 bei den Eltern ausgezogen.", exKo:"그는 스무 살에 부모님 집에서 독립했어요."},
  {id:"v170", de:"renovieren", gr:"hat renoviert", ko:"수리(리모델링)하다", ex:"Wir renovieren gerade die Küche.", exKo:"우리는 지금 부엌을 고치고 있어요."},
  {id:"v171", de:"der Beruf", pl:"Berufe", ko:"직업", ex:"Was sind Sie von Beruf?", exKo:"직업이 어떻게 되세요?"},
  {id:"v172", de:"die Erfahrung", pl:"Erfahrungen", ko:"경험", ex:"Er hat viel Erfahrung in diesem Bereich.", exKo:"그는 이 분야에 경험이 많아요."},
  {id:"v173", de:"die Bewerbung", pl:"Bewerbungen", ko:"지원(서)", ex:"Ich schreibe gerade eine Bewerbung.", exKo:"지금 지원서를 쓰고 있어요."},
  {id:"v174", de:"der Lebenslauf", pl:"Lebensläufe", ko:"이력서", ex:"Schicken Sie uns Ihren Lebenslauf.", exKo:"이력서를 보내 주세요."},
  {id:"v175", de:"das Vorstellungsgespräch", pl:"Vorstellungsgespräche", ko:"면접", ex:"Morgen habe ich ein Vorstellungsgespräch.", exKo:"내일 면접이 있어요."},
  {id:"v176", de:"der Arbeitgeber", pl:"Arbeitgeber", ko:"고용주", ex:"Mein Arbeitgeber ist sehr fair.", exKo:"우리 고용주는 아주 공정해요."},
  {id:"v177", de:"der Mitarbeiter", pl:"Mitarbeiter", ko:"직원", ex:"Die Firma hat 50 Mitarbeiter.", exKo:"그 회사는 직원이 50명이에요."},
  {id:"v178", de:"die Überstunde", pl:"Überstunden", ko:"초과근무", ex:"Ich mache diese Woche viele Überstunden.", exKo:"이번 주에 야근을 많이 해요."},
  {id:"v179", de:"der Feierabend", ko:"퇴근 (후 시간)", ex:"Schönen Feierabend!", exKo:"퇴근 잘하세요!"},
  {id:"v180", de:"die Pause", pl:"Pausen", ko:"휴식", ex:"Machen wir eine kurze Pause.", exKo:"잠깐 쉬어요."},
  {id:"v181", de:"die Übung", pl:"Übungen", ko:"연습 (문제)", ex:"Übung macht den Meister.", exKo:"연습이 대가를 만든다."},
  {id:"v182", de:"der Fehler", pl:"Fehler", ko:"실수", ex:"Fehler sind ganz normal.", exKo:"실수는 아주 정상이에요."},
  {id:"v183", de:"die Bedeutung", pl:"Bedeutungen", ko:"의미", ex:"Dieses Wort hat zwei Bedeutungen.", exKo:"이 단어는 뜻이 두 개예요."},
  {id:"v184", de:"der Satz", pl:"Sätze", ko:"문장", ex:"Bilden Sie einen Satz.", exKo:"문장을 만들어 보세요."},
  {id:"v185", de:"die Aufgabe", pl:"Aufgaben", ko:"과제, 문제", ex:"Die Aufgabe ist nicht schwer.", exKo:"그 문제는 어렵지 않아요."},
  {id:"v186", de:"das Beispiel", pl:"Beispiele", ko:"예시", ex:"Geben Sie ein Beispiel.", exKo:"예를 들어 주세요."},
  {id:"v187", de:"das Zeugnis", pl:"Zeugnisse", ko:"성적표, 증명서", ex:"Ich brauche ein Zeugnis von der Schule.", exKo:"학교 증명서가 필요해요."},
  {id:"v188", de:"die Note", pl:"Noten", ko:"성적", ex:"Sie hat gute Noten.", exKo:"그녀는 성적이 좋아요."},
  {id:"v189", de:"das Niveau", pl:"Niveaus", ko:"수준", ex:"Mein Deutsch ist auf A2-Niveau.", exKo:"내 독일어는 A2 수준이에요."},
  {id:"v190", de:"die Muttersprache", pl:"Muttersprachen", ko:"모국어", ex:"Meine Muttersprache ist Koreanisch.", exKo:"제 모국어는 한국어예요."},
  {id:"v191", de:"der Vermieter", pl:"Vermieter", ko:"집주인", ex:"Der Vermieter wohnt im Erdgeschoss.", exKo:"집주인은 1층에 살아요."},
  {id:"v192", de:"der Mieter", pl:"Mieter", ko:"세입자", ex:"Die Mieter sind sehr ruhig.", exKo:"세입자들이 아주 조용해요."},
  {id:"v193", de:"die Nebenkosten", gr:"항상 복수로 사용", ko:"관리비", ex:"Die Nebenkosten sind ziemlich hoch.", exKo:"관리비가 꽤 비싸요."},
  {id:"v194", de:"die Kaution", pl:"Kautionen", ko:"보증금", ex:"Die Kaution beträgt zwei Monatsmieten.", exKo:"보증금은 두 달치 월세예요."},
  {id:"v195", de:"der Umzug", pl:"Umzüge", ko:"이사", ex:"Der Umzug war anstrengend.", exKo:"이사가 힘들었어요."},
  {id:"v196", de:"die Möbel", gr:"항상 복수로 사용", ko:"가구", ex:"Die Möbel sind neu.", exKo:"가구가 새것이에요."},
  {id:"v197", de:"der Kühlschrank", pl:"Kühlschränke", ko:"냉장고", ex:"Der Kühlschrank ist leer.", exKo:"냉장고가 텅 비었어요."},
  {id:"v198", de:"die Waschmaschine", pl:"Waschmaschinen", ko:"세탁기", ex:"Die Waschmaschine läuft gerade.", exKo:"세탁기가 지금 돌아가고 있어요."},
  {id:"v199", de:"der Herd", pl:"Herde", ko:"레인지, 가스레인지", ex:"Der Herd ist noch an!", exKo:"레인지가 아직 켜져 있어!"},
  {id:"v200", de:"die Spülmaschine", pl:"Spülmaschinen", ko:"식기세척기", ex:"Räum bitte die Spülmaschine aus.", exKo:"식기세척기 좀 비워 줘."},
  {id:"v201", de:"der Stock", pl:"Stockwerke", ko:"층", ex:"Wir wohnen im dritten Stock.", exKo:"우리는 3층에 살아요."},
  {id:"v202", de:"der Lärm", ko:"소음", ex:"Der Lärm von der Straße stört mich.", exKo:"길에서 나는 소음이 거슬려요."},
  {id:"v203", de:"die Ruhe", ko:"조용함, 안정", ex:"Ich brauche jetzt etwas Ruhe.", exKo:"지금은 좀 조용히 쉬고 싶어요."},
  {id:"v204", de:"der Haushalt", pl:"Haushalte", ko:"살림, 가사", ex:"Wir teilen uns den Haushalt.", exKo:"우리는 집안일을 나눠서 해요."},
  {id:"v205", de:"das Geschäft", pl:"Geschäfte", ko:"가게, 사업", ex:"Das Geschäft öffnet um neun.", exKo:"가게는 9시에 열어요."},
  {id:"v206", de:"der Laden", pl:"Läden", ko:"상점", ex:"Der kleine Laden an der Ecke ist toll.", exKo:"모퉁이의 작은 가게가 참 좋아요."},
  {id:"v207", de:"die Öffnungszeiten", gr:"항상 복수로 사용", ko:"영업시간", ex:"Die Öffnungszeiten stehen an der Tür.", exKo:"영업시간은 문에 적혀 있어요."},
  {id:"v208", de:"der Preis", pl:"Preise", ko:"가격", ex:"Die Preise sind gestiegen.", exKo:"물가가 올랐어요."},
  {id:"v209", de:"die Quittung", pl:"Quittungen", ko:"영수증", ex:"Brauchen Sie eine Quittung?", exKo:"영수증 필요하세요?"},
  {id:"v210", de:"der Rabatt", pl:"Rabatte", ko:"할인", ex:"Es gibt heute 20 Prozent Rabatt.", exKo:"오늘 20% 할인해요."},
  {id:"v211", de:"die Größe", pl:"Größen", ko:"사이즈, 크기", ex:"Haben Sie das in Größe M?", exKo:"이거 M 사이즈 있어요?"},
  {id:"v212", de:"die Lebensmittel", gr:"항상 복수로 사용", ko:"식료품", ex:"Ich kaufe Lebensmittel für die Woche.", exKo:"일주일치 장을 봐요."},
  {id:"v213", de:"das Gemüse", ko:"채소", ex:"Iss mehr Gemüse!", exKo:"채소를 더 먹어!"},
  {id:"v214", de:"das Obst", ko:"과일", ex:"Obst ist gesund.", exKo:"과일은 건강에 좋아요."},
  {id:"v215", de:"das Fleisch", ko:"고기", ex:"Ich esse wenig Fleisch.", exKo:"나는 고기를 적게 먹어요."},
  {id:"v216", de:"der Fisch", pl:"Fische", ko:"생선", ex:"Freitags gibt es Fisch.", exKo:"금요일마다 생선이 나와요."},
  {id:"v217", de:"das Getränk", pl:"Getränke", ko:"음료", ex:"Die Getränke sind im Kühlschrank.", exKo:"음료는 냉장고에 있어요."},
  {id:"v218", de:"die Speisekarte", pl:"Speisekarten", ko:"메뉴판", ex:"Die Speisekarte, bitte.", exKo:"메뉴판 좀 주세요."},
  {id:"v219", de:"das Trinkgeld", pl:"Trinkgelder", ko:"팁", ex:"In Deutschland gibt man etwa zehn Prozent Trinkgeld.", exKo:"독일에서는 팁을 10% 정도 줘요."},
  {id:"v220", de:"der Kellner", pl:"Kellner", ko:"웨이터", ex:"Der Kellner war sehr freundlich.", exKo:"웨이터가 아주 친절했어요."},
  {id:"v221", de:"die Reise", pl:"Reisen", ko:"여행", ex:"Gute Reise!", exKo:"좋은 여행 되세요!"},
  {id:"v222", de:"das Reisebüro", pl:"Reisebüros", ko:"여행사", ex:"Wir buchen im Reisebüro.", exKo:"우리는 여행사에서 예약해요."},
  {id:"v223", de:"die Unterkunft", pl:"Unterkünfte", ko:"숙소", ex:"Wir suchen noch eine Unterkunft.", exKo:"아직 숙소를 찾고 있어요."},
  {id:"v224", de:"die Übernachtung", pl:"Übernachtungen", ko:"숙박", ex:"Der Preis gilt pro Übernachtung.", exKo:"가격은 1박 기준이에요."},
  {id:"v225", de:"das Gepäck", ko:"짐, 수하물", ex:"Mein Gepäck ist noch nicht da.", exKo:"제 짐이 아직 안 왔어요."},
  {id:"v226", de:"der Koffer", pl:"Koffer", ko:"캐리어", ex:"Ich packe meinen Koffer.", exKo:"캐리어에 짐을 싸요."},
  {id:"v227", de:"der Ausflug", pl:"Ausflüge", ko:"소풍, 나들이", ex:"Am Samstag machen wir einen Ausflug.", exKo:"토요일에 나들이를 가요."},
  {id:"v228", de:"die Sehenswürdigkeit", pl:"Sehenswürdigkeiten", ko:"관광명소", ex:"Berlin hat viele Sehenswürdigkeiten.", exKo:"베를린엔 볼거리가 많아요."},
  {id:"v229", de:"der Stau", pl:"Staus", ko:"교통체증", ex:"Wir stehen seit einer Stunde im Stau.", exKo:"한 시간째 차가 막혀요."},
  {id:"v230", de:"die Autobahn", pl:"Autobahnen", ko:"고속도로", ex:"Auf der Autobahn war viel Verkehr.", exKo:"고속도로에 차가 많았어요."},
  {id:"v231", de:"die Tankstelle", pl:"Tankstellen", ko:"주유소", ex:"Wir müssen zur Tankstelle.", exKo:"주유소에 가야 해요."},
  {id:"v232", de:"der Unfall", pl:"Unfälle", ko:"사고", ex:"Es gab einen Unfall auf der A3.", exKo:"A3 고속도로에서 사고가 났어요."},
  {id:"v233", de:"die Panne", pl:"Pannen", ko:"(차) 고장", ex:"Wir hatten unterwegs eine Panne.", exKo:"가는 길에 차가 고장 났어요."},
  {id:"v234", de:"die Richtung", pl:"Richtungen", ko:"방향", ex:"In welche Richtung fahren Sie?", exKo:"어느 방향으로 가세요?"},
  {id:"v235", de:"die Kreuzung", pl:"Kreuzungen", ko:"교차로", ex:"An der Kreuzung links abbiegen.", exKo:"교차로에서 좌회전하세요."},
  {id:"v236", de:"die Ampel", pl:"Ampeln", ko:"신호등", ex:"Die Ampel ist rot.", exKo:"신호등이 빨간불이에요."},
  {id:"v237", de:"die Krankheit", pl:"Krankheiten", ko:"질병", ex:"Die Krankheit ist nicht gefährlich.", exKo:"그 병은 위험하지 않아요."},
  {id:"v238", de:"die Grippe", ko:"독감", ex:"Ich habe die Grippe.", exKo:"독감에 걸렸어요."},
  {id:"v239", de:"der Husten", ko:"기침", ex:"Der Husten wird nicht besser.", exKo:"기침이 낫지를 않아요."},
  {id:"v240", de:"der Schnupfen", ko:"콧물감기", ex:"Ich habe nur einen Schnupfen.", exKo:"그냥 콧물감기예요."},
  {id:"v241", de:"die Salbe", pl:"Salben", ko:"연고", ex:"Die Salbe hilft gegen die Schmerzen.", exKo:"이 연고가 통증에 효과 있어요."},
  {id:"v242", de:"die Tablette", pl:"Tabletten", ko:"알약", ex:"Nehmen Sie die Tabletten nach dem Essen.", exKo:"약은 식후에 드세요."},
  {id:"v243", de:"die Spritze", pl:"Spritzen", ko:"주사", ex:"Ich habe eine Spritze bekommen.", exKo:"주사를 맞았어요."},
  {id:"v244", de:"die Untersuchung", pl:"Untersuchungen", ko:"검진", ex:"Die Untersuchung dauert 20 Minuten.", exKo:"검진은 20분 걸려요."},
  {id:"v245", de:"der Zahnarzt", pl:"Zahnärzte", ko:"치과의사", ex:"Ich muss zum Zahnarzt.", exKo:"치과에 가야 해요."},
  {id:"v246", de:"das Krankenhaus", pl:"Krankenhäuser", ko:"병원 (입원)", ex:"Er liegt im Krankenhaus.", exKo:"그는 입원 중이에요."},
  {id:"v247", de:"der Notfall", pl:"Notfälle", ko:"응급상황", ex:"Im Notfall rufen Sie die 112 an.", exKo:"응급상황엔 112에 전화하세요."},
  {id:"v248", de:"die Krankenkasse", pl:"Krankenkassen", ko:"(공보험) 의료보험", ex:"Die Krankenkasse bezahlt die Behandlung.", exKo:"치료비는 의료보험이 내요."},
  {id:"v249", de:"die Nachrichten", gr:"항상 복수로 사용", ko:"뉴스", ex:"Ich sehe abends die Nachrichten.", exKo:"저녁에 뉴스를 봐요."},
  {id:"v250", de:"die Sendung", pl:"Sendungen", ko:"방송 (프로그램)", ex:"Die Sendung kommt um 20:15 Uhr.", exKo:"그 방송은 20시 15분에 해요."},
  {id:"v251", de:"die Werbung", ko:"광고", ex:"Zu viel Werbung nervt.", exKo:"광고가 너무 많으면 짜증나요."},
  {id:"v252", de:"der Drucker", pl:"Drucker", ko:"프린터", ex:"Der Drucker hat kein Papier mehr.", exKo:"프린터에 종이가 다 떨어졌어요."},
  {id:"v253", de:"der Bildschirm", pl:"Bildschirme", ko:"화면, 모니터", ex:"Der Bildschirm ist zu dunkel.", exKo:"화면이 너무 어두워요."},
  {id:"v254", de:"die Datei", pl:"Dateien", ko:"파일", ex:"Ich schicke dir die Datei per E-Mail.", exKo:"파일을 이메일로 보낼게."},
  {id:"v255", de:"das Passwort", pl:"Passwörter", ko:"비밀번호", ex:"Ich habe mein Passwort vergessen.", exKo:"비밀번호를 잊어버렸어요."},
  {id:"v256", de:"der Anhang", pl:"Anhänge", ko:"첨부파일", ex:"Die Rechnung ist im Anhang.", exKo:"청구서는 첨부파일에 있어요."},
  {id:"v257", de:"die Verbindung", pl:"Verbindungen", ko:"연결, 접속", ex:"Die Internetverbindung ist schlecht.", exKo:"인터넷 연결이 안 좋아요."},
  {id:"v258", de:"das Amt", pl:"Ämter", ko:"관청", ex:"Ich muss morgen aufs Amt.", exKo:"내일 관청에 가야 해요."},
  {id:"v259", de:"die Behörde", pl:"Behörden", ko:"관공서", ex:"Die Behörde hat nur vormittags geöffnet.", exKo:"그 관공서는 오전에만 열어요."},
  {id:"v260", de:"das Konto", pl:"Konten", ko:"계좌", ex:"Ich möchte ein Konto eröffnen.", exKo:"계좌를 개설하고 싶어요."},
  {id:"v261", de:"die Überweisung", pl:"Überweisungen", ko:"계좌이체", ex:"Die Überweisung dauert einen Tag.", exKo:"이체는 하루 걸려요."},
  {id:"v262", de:"das Bargeld", ko:"현금", ex:"Ich habe kein Bargeld dabei.", exKo:"현금을 안 가져왔어요."},
  {id:"v263", de:"die Gebühr", pl:"Gebühren", ko:"수수료", ex:"Die Gebühr beträgt fünf Euro.", exKo:"수수료는 5유로예요."},
  {id:"v264", de:"der Ausländer", pl:"Ausländer", ko:"외국인", ex:"Als Ausländer braucht man viele Dokumente.", exKo:"외국인은 서류가 많이 필요해요."},
  {id:"v265", de:"die Staatsangehörigkeit", pl:"Staatsangehörigkeiten", ko:"국적", ex:"Welche Staatsangehörigkeit haben Sie?", exKo:"국적이 어떻게 되세요?"},
  {id:"v266", de:"die Aufenthaltserlaubnis", ko:"체류허가", ex:"Meine Aufenthaltserlaubnis gilt zwei Jahre.", exKo:"제 체류허가는 2년 유효해요."},
  {id:"v267", de:"die Frist", pl:"Fristen", ko:"기한", ex:"Die Frist endet am Freitag.", exKo:"기한은 금요일까지예요."},
  {id:"v268", de:"die Freude", ko:"기쁨", ex:"Die Kinder machen mir viel Freude.", exKo:"아이들이 큰 기쁨을 줘요."},
  {id:"v269", de:"die Angst", pl:"Ängste", ko:"두려움", ex:"Du musst keine Angst haben.", exKo:"무서워할 필요 없어."},
  {id:"v270", de:"die Sorge", pl:"Sorgen", ko:"걱정", ex:"Mach dir keine Sorgen!", exKo:"걱정하지 마!"},
  {id:"v271", de:"der Stress", ko:"스트레스", ex:"Ich habe gerade viel Stress im Job.", exKo:"요즘 일 때문에 스트레스가 많아요."},
  {id:"v272", de:"die Überraschung", pl:"Überraschungen", ko:"놀람, 서프라이즈", ex:"Was für eine schöne Überraschung!", exKo:"이게 웬 반가운 서프라이즈야!"},
  {id:"v273", de:"die Hochzeit", pl:"Hochzeiten", ko:"결혼식", ex:"Wir sind zur Hochzeit eingeladen.", exKo:"우리는 결혼식에 초대받았어요."},
  {id:"v274", de:"die Ehe", pl:"Ehen", ko:"결혼 (생활)", ex:"Sie führen eine glückliche Ehe.", exKo:"그들은 행복한 결혼 생활을 해요."},
  {id:"v275", de:"der Streit", ko:"다툼", ex:"Wir hatten gestern einen kleinen Streit.", exKo:"우리 어제 좀 다퉜어요."},
  {id:"v276", de:"die Beziehung", pl:"Beziehungen", ko:"관계", ex:"Sie haben eine gute Beziehung.", exKo:"그들은 사이가 좋아요."},
  {id:"v277", de:"der Besuch", pl:"Besuche", ko:"방문, 손님", ex:"Wir bekommen am Wochenende Besuch.", exKo:"주말에 손님이 와요."},
  {id:"v278", de:"die Meinung", pl:"Meinungen", ko:"의견", ex:"Meiner Meinung nach ist das richtig.", exKo:"제 생각엔 그게 맞아요."},
  {id:"v279", de:"der Vorschlag", pl:"Vorschläge", ko:"제안", ex:"Das ist ein guter Vorschlag.", exKo:"좋은 제안이네요."},
  {id:"v280", de:"der Grund", pl:"Gründe", ko:"이유", ex:"Was ist der Grund dafür?", exKo:"그 이유가 뭐예요?"},
  {id:"v281", de:"die Möglichkeit", pl:"Möglichkeiten", ko:"가능성, 방법", ex:"Es gibt zwei Möglichkeiten.", exKo:"방법이 두 가지 있어요."},
  {id:"v282", de:"der Unterschied", pl:"Unterschiede", ko:"차이", ex:"Der Unterschied ist klein.", exKo:"차이는 작아요."},
  {id:"v283", de:"die Umgebung", ko:"주변, 근처", ex:"Die Umgebung ist sehr ruhig.", exKo:"주변이 아주 조용해요."},
  {id:"v284", de:"die Zukunft", ko:"미래", ex:"In der Zukunft möchte ich hier arbeiten.", exKo:"앞으로 여기서 일하고 싶어요."},
  {id:"v285", de:"die Vergangenheit", ko:"과거", ex:"Das ist Vergangenheit.", exKo:"그건 지난 일이에요."},
  {id:"v286", de:"ähnlich", ko:"비슷한", ex:"Wir sind uns sehr ähnlich.", exKo:"우리는 서로 많이 닮았어요."},
  {id:"v287", de:"verschieden", ko:"서로 다른", ex:"Wir haben verschiedene Meinungen.", exKo:"우리는 의견이 서로 달라요."},
  {id:"v288", de:"gleich", ko:"같은; 곧", ex:"Bis gleich!", exKo:"이따 봐!"},
  {id:"v289", de:"eigen", ko:"자신의", ex:"Ich habe endlich ein eigenes Zimmer.", exKo:"드디어 내 방이 생겼어요."},
  {id:"v290", de:"fremd", ko:"낯선", ex:"Die Stadt ist mir noch fremd.", exKo:"이 도시는 아직 낯설어요."},
  {id:"v291", de:"bekannt", ko:"알려진, 익숙한", ex:"Das kommt mir bekannt vor.", exKo:"어디서 본 것 같은데요."},
  {id:"v292", de:"berühmt", ko:"유명한", ex:"Das Schloss ist weltberühmt.", exKo:"그 성은 세계적으로 유명해요."},
  {id:"v293", de:"beliebt", ko:"인기 있는", ex:"Dieses Café ist sehr beliebt.", exKo:"이 카페는 인기가 많아요."},
  {id:"v294", de:"modern", ko:"현대적인", ex:"Die Wohnung ist modern eingerichtet.", exKo:"집이 현대적으로 꾸며져 있어요."},
  {id:"v295", de:"praktisch", ko:"실용적인", ex:"Das ist sehr praktisch.", exKo:"그거 아주 실용적이네요."},
  {id:"v296", de:"nützlich", ko:"유용한", ex:"Die App ist wirklich nützlich.", exKo:"그 앱은 정말 유용해요."},
  {id:"v297", de:"notwendig", ko:"필수적인", ex:"Eine Anmeldung ist notwendig.", exKo:"등록이 필수예요."},
  {id:"v298", de:"geöffnet", ko:"열려 있는", ex:"Sonntags ist die Apotheke nicht geöffnet.", exKo:"일요일에 약국은 안 열어요."},
  {id:"v299", de:"geschlossen", ko:"닫힌", ex:"Das Amt ist heute geschlossen.", exKo:"관청이 오늘 문을 닫았어요."},
  {id:"v300", de:"unbedingt", ko:"꼭, 반드시", ex:"Du musst unbedingt kommen!", exKo:"너 꼭 와야 해!"},
  {id:"v301", de:"wahrscheinlich", ko:"아마 (높은 확률로)", ex:"Er kommt wahrscheinlich später.", exKo:"그는 아마 늦게 올 거예요."},
  {id:"v302", de:"bestimmt", ko:"분명히", ex:"Das klappt bestimmt.", exKo:"분명히 잘될 거예요."},
  {id:"v303", de:"ungefähr", ko:"대략", ex:"Es dauert ungefähr eine Stunde.", exKo:"대략 한 시간 걸려요."},
  {id:"v304", de:"mindestens", ko:"최소한", ex:"Das kostet mindestens 100 Euro.", exKo:"그건 최소 100유로는 해요."},
  {id:"v305", de:"höchstens", ko:"기껏해야", ex:"Es dauert höchstens zehn Minuten.", exKo:"길어야 10분이면 돼요."},
  {id:"v306", de:"sofort", ko:"즉시", ex:"Ich komme sofort!", exKo:"금방 갈게!"},
  {id:"v307", de:"inzwischen", ko:"그 사이에", ex:"Inzwischen spricht er gut Deutsch.", exKo:"그 사이에 그는 독일어를 잘하게 됐어요."},
  {id:"v308", de:"endlich", ko:"마침내", ex:"Endlich ist Wochenende!", exKo:"드디어 주말이다!"},
  {id:"v309", de:"sogar", ko:"심지어", ex:"Er spricht sogar fünf Sprachen.", exKo:"그는 심지어 5개 국어를 해요."},
  {id:"v310", de:"kaum", ko:"거의 ~않다", ex:"Ich habe kaum geschlafen.", exKo:"잠을 거의 못 잤어요."},
  {id:"v311", de:"überall", ko:"어디에나", ex:"In Berlin gibt es überall Baustellen.", exKo:"베를린엔 어디에나 공사장이 있어요."},
  {id:"v312", de:"draußen", ko:"밖에", ex:"Die Kinder spielen draußen.", exKo:"아이들이 밖에서 놀아요."},
  {id:"v313", de:"drinnen", ko:"안에", ex:"Bei Regen bleiben wir drinnen.", exKo:"비가 오면 안에 있어요."},
  {id:"v314", de:"unterwegs", ko:"이동 중에", ex:"Ich bin gerade unterwegs.", exKo:"지금 가는 중이야."},
  {id:"v315", de:"rechtzeitig", ko:"제때에", ex:"Komm bitte rechtzeitig zum Termin.", exKo:"약속에 늦지 않게 와 줘."},
  {id:"v316", de:"zufällig", ko:"우연히", ex:"Ich habe ihn zufällig getroffen.", exKo:"그를 우연히 만났어요."},
  {id:"v317", de:"wirklich", ko:"정말로", ex:"Das ist wirklich lecker!", exKo:"이거 정말 맛있다!"},
  {id:"v318", de:"ziemlich", ko:"꽤", ex:"Der Test war ziemlich schwer.", exKo:"시험이 꽤 어려웠어요."},
  {id:"v319", de:"fast", ko:"거의", ex:"Ich bin fast fertig.", exKo:"거의 다 했어요."},
  {id:"v320", de:"gar nicht", ko:"전혀 ~않다", ex:"Das ist gar nicht schlimm.", exKo:"그거 전혀 심각하지 않아요."},
];

// drills: ko(한국어 문제), de(정답), alt(허용 답안), note(한 줄 문법 설명)
const DRILLS = [
  // Perfekt (haben/sein + 과거분사)
  {id:"d001", ko:"나는 어제 피자를 먹었어요.", de:"Ich habe gestern Pizza gegessen.", note:"과거(Perfekt) = haben + 과거분사(문장 끝). essen → gegessen"},
  {id:"d002", ko:"우리는 프랑크푸르트로 이사했어요.", de:"Wir sind nach Frankfurt umgezogen.", note:"이동·변화 동사는 sein + 과거분사: sind ... umgezogen"},
  {id:"d003", ko:"그는 8시에 일어났어요.", de:"Er ist um acht Uhr aufgestanden.", note:"aufstehen은 sein을 써요: ist aufgestanden"},
  {id:"d004", ko:"너 내 메시지 받았어?", de:"Hast du meine Nachricht bekommen?", note:"be-로 시작하는 동사는 ge- 없이: bekommen"},
  {id:"d005", ko:"무슨 일이 있었어요?", de:"Was ist passiert?", note:"passieren은 sein: ist passiert"},
  {id:"d006", ko:"나는 열쇠를 잃어버렸어요.", de:"Ich habe meinen Schlüssel verloren.", note:"der Schlüssel → 목적어(Akk.)에서 meinen"},
  {id:"d007", ko:"갑자기 비가 왔어요.", de:"Plötzlich hat es geregnet.", note:"Plötzlich이 1번째 → 동사 2번째(hat), 주어 3번째(es)"},
  {id:"d008", ko:"예전에 나는 서울에 살았어요.", de:"Früher habe ich in Seoul gewohnt.", note:"Früher 도치 + Perfekt: habe ... gewohnt"},
  // Präteritum (war/hatte/konnte/musste)
  {id:"d009", ko:"지난주에 나는 아팠어요.", de:"Letzte Woche war ich krank.", note:"sein·haben의 과거는 Präteritum: war / hatte"},
  {id:"d010", ko:"나는 시간이 없었어요.", de:"Ich hatte keine Zeit.", note:"haben의 과거: hatte"},
  {id:"d011", ko:"나는 어제 올 수 없었어요.", de:"Ich konnte gestern nicht kommen.", note:"können의 과거: konnte (+ 동사원형 문미)"},
  {id:"d012", ko:"나는 일해야 했어요.", de:"Ich musste arbeiten.", note:"müssen의 과거: musste"},
  // 부문장 (weil/dass/wenn) — telc 단골
  {id:"d013", ko:"나는 아파서 집에 있어요.", de:"Ich bleibe zu Hause, weil ich krank bin.", note:"weil 부문장에서는 동사가 맨 끝으로!"},
  {id:"d014", ko:"나는 그가 옳다고 생각해요.", de:"Ich glaube, dass er recht hat.", note:"dass 부문장도 동사가 맨 끝: ... recht hat"},
  {id:"d015", ko:"비가 오면 나는 버스를 타요.", de:"Wenn es regnet, nehme ich den Bus.", note:"Wenn절이 앞에 오면 주절은 동사부터: ..., nehme ich ..."},
  {id:"d016", ko:"나는 피곤해서 일찍 잤어요.", de:"Ich war müde, deshalb bin ich früh ins Bett gegangen.", note:"deshalb 뒤에는 도치: deshalb bin ich ..."},
  {id:"d017", ko:"비가 오지만 그래도 우리는 산책해요.", de:"Es regnet, trotzdem gehen wir spazieren.", note:"trotzdem 뒤에도 도치: trotzdem gehen wir ..."},
  // Dativ 동사
  {id:"d018", ko:"프랑크푸르트가 마음에 들어요.", de:"Frankfurt gefällt mir.", alt:["Frankfurt gefällt mir gut."], note:"gefallen은 Dativ와 함께: mir (mich 아님!)"},
  {id:"d019", ko:"그 휴대폰은 내 거예요.", de:"Das Handy gehört mir.", note:"gehören + Dativ: mir"},
  {id:"d020", ko:"머리가 아파요.", de:"Ich habe Kopfschmerzen.", note:"아픔 표현: ~schmerzen haben (항상 복수)"},
  // 분리동사
  {id:"d021", ko:"내일 전화할게.", de:"Ich rufe dich morgen an.", note:"분리동사: 접두사(an)는 문장 맨 끝으로"},
  {id:"d022", ko:"버스가 곧 출발해요.", de:"Der Bus fährt gleich ab.", note:"abfahren → fährt ... ab"},
  {id:"d023", ko:"프랑크푸르트에서 갈아타셔야 해요.", de:"Sie müssen in Frankfurt umsteigen.", note:"조동사가 있으면 분리동사는 붙인 채 문미: umsteigen"},
  {id:"d024", ko:"기차역으로 데리러 갈게.", de:"Ich hole dich vom Bahnhof ab.", note:"abholen → hole ... ab. vom = von + dem"},
  {id:"d025", ko:"이 서식을 작성해 주세요.", de:"Bitte füllen Sie das Formular aus.", alt:["Füllen Sie bitte das Formular aus."], note:"존칭 명령 + 분리동사: füllen Sie ... aus"},
  // 재귀동사
  {id:"d026", ko:"주말이 기대돼요.", de:"Ich freue mich auf das Wochenende.", note:"sich freuen auf + Akkusativ = ~을 기대하다"},
  {id:"d027", ko:"우리는 7시에 만나요.", de:"Wir treffen uns um sieben.", alt:["Wir treffen uns um sieben Uhr.", "Wir treffen uns um 7 Uhr."], note:"sich treffen: wir → uns"},
  {id:"d028", ko:"오늘은 몸이 좀 나아요.", de:"Ich fühle mich heute besser.", note:"sich fühlen + 비교급 besser(gut의 비교급)"},
  // 비교급
  {id:"d029", ko:"독일어가 영어보다 어려워요.", de:"Deutsch ist schwieriger als Englisch.", note:"비교급 = 형용사 + -er + als"},
  {id:"d030", ko:"오늘이 어제보다 따뜻해요.", de:"Heute ist es wärmer als gestern.", note:"warm → wärmer (a는 움라우트로!)"},
  {id:"d031", ko:"날씨가 내일 나아질 거예요.", de:"Das Wetter wird morgen besser.", note:"gut → besser (불규칙 비교급)"},
  // 생활 실전 문장
  {id:"d032", ko:"기차가 20분 연착이에요.", de:"Der Zug hat zwanzig Minuten Verspätung.", alt:["Der Zug hat 20 Minuten Verspätung."], note:"연착 표현: Verspätung haben"},
  {id:"d033", ko:"카드로 계산해도 되나요?", de:"Kann ich mit Karte bezahlen?", note:"mit Karte / bar(현금으로) bezahlen"},
  {id:"d034", ko:"계산서 주세요!", de:"Die Rechnung, bitte!", note:"식당에서 계산할 때 그대로 쓰는 표현"},
  {id:"d035", ko:"이 자리 비어 있나요?", de:"Ist dieser Platz noch frei?", alt:["Ist der Platz noch frei?"], note:"dieser Platz(남성 주격). 대답: Ja, bitte! / Nein, besetzt."},
  {id:"d036", ko:"난방이 안 돼요.", de:"Die Heizung funktioniert nicht.", note:"고장 신고 표현: funktioniert nicht = 작동 안 함"},
  {id:"d037", ko:"그는 시험에 합격했어요.", de:"Er hat die Prüfung bestanden.", note:"bestehen(합격하다) → hat bestanden"},
  {id:"d038", ko:"월세가 너무 비싸요.", de:"Die Miete ist zu hoch.", note:"월세·가격이 '비싸다'는 teuer가 아니라 hoch"},
  {id:"d039", ko:"이 약을 하루 세 번 드세요.", de:"Nehmen Sie das Medikament dreimal täglich.", note:"존칭 명령문: Nehmen Sie ..."},
  {id:"d040", ko:"초대해 줘서 고마워요!", de:"Danke für die Einladung!", note:"danke für + Akkusativ"},
];
