// telc B1 스프린트 — 배치 1: A2 핵심 (A1은 건너뜀)
// vocab: de(표제어), pl(복수), gr(불규칙 3인칭·과거분사 등 문법정보), ko(뜻), ex(예문), exKo(예문 뜻)
const VOCAB = [
  // ---- 분리동사 · 일상 동사 (Perfekt 정보 포함) ----
  {id:"v001", de:"anfangen", gr:"er fängt an · hat angefangen", ko:"시작하다", ex:"Der Kurs fängt um neun an.", exKo:"수업은 9시에 시작해요."},
  {id:"v002", de:"aufhören", gr:"hat aufgehört", ko:"그만두다, 끝나다", ex:"Hör bitte auf!", exKo:"제발 그만해!"},
  {id:"v003", de:"anrufen", gr:"hat angerufen", ko:"전화하다", ex:"Ich rufe dich morgen an.", exKo:"내일 전화할게."},
  {id:"v004", de:"abholen", gr:"hat abgeholt", ko:"데리러 가다, 찾아오다", ex:"Ich hole dich vom Bahnhof ab.", exKo:"기차역으로 데리러 갈게."},
  {id:"v005", de:"einkaufen", gr:"hat eingekauft", ko:"장을 보다", ex:"Samstags kaufen wir im Supermarkt ein.", exKo:"토요일마다 우리는 슈퍼에서 장을 봐요."},
  {id:"v006", de:"aufstehen", gr:"ist aufgestanden", ko:"일어나다", ex:"Ich stehe jeden Tag um sechs auf.", exKo:"나는 매일 6시에 일어나요."},
  {id:"v007", de:"fernsehen", gr:"er sieht fern · hat ferngesehen", ko:"텔레비전을 보다", ex:"Abends sehe ich oft fern.", exKo:"저녁에 나는 자주 TV를 봐요."},
  {id:"v008", de:"mitbringen", gr:"hat mitgebracht", ko:"가져오다", ex:"Was soll ich zur Party mitbringen?", exKo:"파티에 뭘 가져갈까?"},
  {id:"v009", de:"einladen", gr:"er lädt ein · hat eingeladen", ko:"초대하다", ex:"Ich lade dich zum Essen ein.", exKo:"내가 식사에 초대할게(밥 살게)."},
  {id:"v010", de:"ankommen", gr:"ist angekommen", ko:"도착하다", ex:"Der Zug ist pünktlich angekommen.", exKo:"기차가 제시간에 도착했어요."},
  {id:"v011", de:"abfahren", gr:"er fährt ab · ist abgefahren", ko:"출발하다", ex:"Der Bus fährt gleich ab.", exKo:"버스가 곧 출발해요."},
  {id:"v012", de:"einsteigen", gr:"ist eingestiegen", ko:"(탈것에) 타다", ex:"Bitte einsteigen!", exKo:"탑승해 주세요!"},
  {id:"v013", de:"aussteigen", gr:"ist ausgestiegen", ko:"내리다", ex:"Wir steigen an der nächsten Haltestelle aus.", exKo:"우리는 다음 정류장에서 내려요."},
  {id:"v014", de:"umsteigen", gr:"ist umgestiegen", ko:"갈아타다", ex:"Sie müssen in Frankfurt umsteigen.", exKo:"프랑크푸르트에서 갈아타셔야 해요."},
  {id:"v015", de:"bekommen", gr:"hat bekommen", ko:"받다", ex:"Ich habe deine Nachricht bekommen.", exKo:"네 메시지 받았어."},
  {id:"v016", de:"bezahlen", gr:"hat bezahlt", ko:"지불하다", ex:"Kann ich mit Karte bezahlen?", exKo:"카드로 계산해도 되나요?"},
  {id:"v017", de:"bestellen", gr:"hat bestellt", ko:"주문하다", ex:"Ich habe schon bestellt.", exKo:"저는 이미 주문했어요."},
  {id:"v018", de:"erklären", gr:"hat erklärt", ko:"설명하다", ex:"Können Sie das bitte erklären?", exKo:"그걸 설명해 주시겠어요?"},
  {id:"v019", de:"erzählen", gr:"hat erzählt", ko:"이야기해 주다", ex:"Erzähl mal!", exKo:"얘기해 봐!"},
  {id:"v020", de:"vergessen", gr:"er vergisst · hat vergessen", ko:"잊다", ex:"Ich habe den Termin vergessen.", exKo:"나는 그 약속을 잊어버렸어요."},
  {id:"v021", de:"verlieren", gr:"hat verloren", ko:"잃어버리다", ex:"Ich habe meinen Schlüssel verloren.", exKo:"나는 열쇠를 잃어버렸어요."},
  {id:"v022", de:"versuchen", gr:"hat versucht", ko:"시도하다", ex:"Ich versuche es noch einmal.", exKo:"한 번 더 해볼게요."},
  {id:"v023", de:"passieren", gr:"ist passiert", ko:"(일이) 일어나다", ex:"Was ist passiert?", exKo:"무슨 일이 있었어요?"},
  {id:"v024", de:"gehören", gr:"+ Dativ · hat gehört", ko:"~의 것이다", ex:"Das Handy gehört mir.", exKo:"그 휴대폰은 내 거예요."},
  {id:"v025", de:"gefallen", gr:"+ Dativ · er gefällt · hat gefallen", ko:"마음에 들다", ex:"Frankfurt gefällt mir gut.", exKo:"프랑크푸르트가 마음에 들어요."},
  {id:"v026", de:"schmecken", gr:"hat geschmeckt", ko:"맛이 ~하다", ex:"Hat es geschmeckt?", exKo:"맛있었어요?"},
  {id:"v027", de:"wehtun", gr:"hat wehgetan", ko:"아프다", ex:"Mein Rücken tut weh.", exKo:"허리가 아파요."},
  {id:"v028", de:"sich freuen", gr:"auf + Akk · hat sich gefreut", ko:"기뻐하다, 기대하다", ex:"Ich freue mich auf das Wochenende.", exKo:"주말이 기대돼요."},
  {id:"v029", de:"sich treffen", gr:"er trifft sich · hat sich getroffen", ko:"만나다", ex:"Wir treffen uns um sieben.", exKo:"우리는 7시에 만나요."},
  {id:"v030", de:"sich fühlen", gr:"hat sich gefühlt", ko:"(몸·기분을) 느끼다", ex:"Ich fühle mich heute besser.", exKo:"오늘은 몸이 좀 나아요."},
  {id:"v031", de:"umziehen", gr:"ist umgezogen", ko:"이사하다", ex:"Wir sind nach Frankfurt umgezogen.", exKo:"우리는 프랑크푸르트로 이사했어요."},
  {id:"v032", de:"mieten", gr:"hat gemietet", ko:"세내다, 빌리다", ex:"Wir haben eine Wohnung gemietet.", exKo:"우리는 집을 하나 빌렸어요."},
  {id:"v033", de:"reparieren", gr:"hat repariert", ko:"수리하다", ex:"Er repariert gerade das Auto.", exKo:"그는 지금 차를 수리하고 있어요."},
  {id:"v034", de:"schicken", gr:"hat geschickt", ko:"보내다", ex:"Ich schicke dir die Adresse.", exKo:"주소 보내줄게."},
  {id:"v035", de:"warten", gr:"auf + Akk · hat gewartet", ko:"기다리다", ex:"Wir warten auf den Bus.", exKo:"우리는 버스를 기다리고 있어요."},
  // ---- 명사: 교통 · 관공서 · 집 · 직장 · 건강 ----
  {id:"v036", de:"der Flughafen", pl:"Flughäfen", ko:"공항", ex:"Der Flughafen ist weit weg.", exKo:"공항은 멀리 있어요."},
  {id:"v037", de:"die Haltestelle", pl:"Haltestellen", ko:"정류장", ex:"Wo ist die nächste Haltestelle?", exKo:"가장 가까운 정류장이 어디예요?"},
  {id:"v038", de:"die Verspätung", pl:"Verspätungen", ko:"연착, 지연", ex:"Der Zug hat zwanzig Minuten Verspätung.", exKo:"기차가 20분 연착이에요."},
  {id:"v039", de:"die Fahrkarte", pl:"Fahrkarten", ko:"승차권", ex:"Ich habe die Fahrkarte schon gekauft.", exKo:"표는 이미 샀어요."},
  {id:"v040", de:"der Führerschein", pl:"Führerscheine", ko:"운전면허증", ex:"Er macht gerade den Führerschein.", exKo:"그는 지금 운전면허를 따고 있어요."},
  {id:"v041", de:"der Ausweis", pl:"Ausweise", ko:"신분증", ex:"Ihren Ausweis, bitte.", exKo:"신분증 부탁드립니다."},
  {id:"v042", de:"die Anmeldung", pl:"Anmeldungen", ko:"등록, 신고", ex:"Die Anmeldung ist kostenlos.", exKo:"등록은 무료예요."},
  {id:"v043", de:"das Formular", pl:"Formulare", ko:"서식, 양식", ex:"Bitte füllen Sie das Formular aus.", exKo:"이 서식을 작성해 주세요."},
  {id:"v044", de:"die Unterschrift", pl:"Unterschriften", ko:"서명", ex:"Ich brauche noch Ihre Unterschrift.", exKo:"서명이 아직 필요해요."},
  {id:"v045", de:"der Vertrag", pl:"Verträge", ko:"계약(서)", ex:"Ich habe den Vertrag unterschrieben.", exKo:"나는 계약서에 서명했어요."},
  {id:"v046", de:"die Miete", pl:"Mieten", ko:"월세", ex:"Die Miete ist sehr hoch.", exKo:"월세가 아주 비싸요."},
  {id:"v047", de:"der Nachbar", pl:"Nachbarn", ko:"이웃", ex:"Unsere Nachbarn sind sehr freundlich.", exKo:"우리 이웃들은 아주 친절해요."},
  {id:"v048", de:"der Schlüssel", pl:"Schlüssel", ko:"열쇠", ex:"Wo ist mein Schlüssel?", exKo:"내 열쇠 어디 있지?"},
  {id:"v049", de:"die Rechnung", pl:"Rechnungen", ko:"계산서, 청구서", ex:"Die Rechnung, bitte!", exKo:"계산서 주세요!"},
  {id:"v050", de:"das Angebot", pl:"Angebote", ko:"할인 상품, 제안", ex:"Das ist ein gutes Angebot.", exKo:"좋은 조건(할인)이네요."},
  {id:"v051", de:"der Kunde", pl:"Kunden", ko:"고객", ex:"Der Kunde ist König.", exKo:"고객은 왕이다."},
  {id:"v052", de:"die Gesundheit", ko:"건강", ex:"Rauchen ist schlecht für die Gesundheit.", exKo:"흡연은 건강에 나빠요."},
  {id:"v053", de:"das Fieber", ko:"열", ex:"Das Kind hat hohes Fieber.", exKo:"아이가 열이 높아요."},
  {id:"v054", de:"die Erkältung", pl:"Erkältungen", ko:"감기", ex:"Ich habe eine Erkältung.", exKo:"나 감기 걸렸어요."},
  {id:"v055", de:"der Schmerz", pl:"Schmerzen", ko:"통증", ex:"Ich habe starke Schmerzen.", exKo:"통증이 심해요."},
  {id:"v056", de:"die Apotheke", pl:"Apotheken", ko:"약국", ex:"Die Apotheke ist gleich um die Ecke.", exKo:"약국은 바로 모퉁이에 있어요."},
  {id:"v057", de:"das Medikament", pl:"Medikamente", ko:"약", ex:"Nehmen Sie das Medikament dreimal täglich.", exKo:"이 약을 하루 세 번 드세요."},
  {id:"v058", de:"das Rezept", pl:"Rezepte", ko:"처방전; 요리법", ex:"Dieses Medikament gibt es nur auf Rezept.", exKo:"이 약은 처방전이 있어야만 살 수 있어요."},
  {id:"v059", de:"die Versicherung", pl:"Versicherungen", ko:"보험", ex:"Die Versicherung bezahlt das.", exKo:"그건 보험이 지불해요."},
  {id:"v060", de:"die Prüfung", pl:"Prüfungen", ko:"시험", ex:"Er hat die Prüfung bestanden.", exKo:"그는 시험에 합격했어요."},
  {id:"v061", de:"die Ausbildung", pl:"Ausbildungen", ko:"직업교육", ex:"Sie macht eine Ausbildung.", exKo:"그녀는 직업교육을 받고 있어요."},
  {id:"v062", de:"das Gehalt", pl:"Gehälter", ko:"월급", ex:"Das Gehalt ist nicht schlecht.", exKo:"월급이 나쁘지 않아요."},
  {id:"v063", de:"die Stelle", pl:"Stellen", ko:"일자리", ex:"Er sucht eine neue Stelle.", exKo:"그는 새 일자리를 찾고 있어요."},
  {id:"v064", de:"der Chef", pl:"Chefs", ko:"상사, 사장", ex:"Mein Chef ist heute nicht da.", exKo:"우리 사장님은 오늘 안 계세요."},
  {id:"v065", de:"der Kollege", pl:"Kollegen", ko:"동료", ex:"Meine Kollegen sind nett.", exKo:"내 동료들은 친절해요."},
  {id:"v066", de:"die Besprechung", pl:"Besprechungen", ko:"회의", ex:"Die Besprechung dauert eine Stunde.", exKo:"회의는 한 시간 걸려요."},
  {id:"v067", de:"der Feiertag", pl:"Feiertage", ko:"공휴일", ex:"Morgen ist ein Feiertag.", exKo:"내일은 공휴일이에요."},
  {id:"v068", de:"das Wetter", ko:"날씨", ex:"Das Wetter wird morgen besser.", exKo:"날씨가 내일 나아질 거예요."},
  {id:"v069", de:"der Regen", ko:"비", ex:"Bei Regen bleiben wir zu Hause.", exKo:"비가 오면 우리는 집에 있어요."},
  {id:"v070", de:"der Schnee", ko:"눈(雪)", ex:"Im Winter gibt es hier viel Schnee.", exKo:"겨울에 여기는 눈이 많이 와요."},
  {id:"v071", de:"die Umwelt", ko:"환경", ex:"Das ist gut für die Umwelt.", exKo:"그건 환경에 좋아요."},
  {id:"v072", de:"der Müll", ko:"쓰레기", ex:"Bitte trennen Sie den Müll.", exKo:"쓰레기를 분리해 주세요."},
  {id:"v073", de:"die Heizung", pl:"Heizungen", ko:"난방", ex:"Die Heizung funktioniert nicht.", exKo:"난방이 안 돼요."},
  {id:"v074", de:"der Aufzug", pl:"Aufzüge", ko:"엘리베이터", ex:"Der Aufzug ist kaputt.", exKo:"엘리베이터가 고장 났어요."},
  {id:"v075", de:"das Erdgeschoss", pl:"Erdgeschosse", ko:"1층(지상층)", ex:"Wir wohnen im Erdgeschoss.", exKo:"우리는 1층에 살아요."},
  {id:"v076", de:"der Keller", pl:"Keller", ko:"지하실", ex:"Die Fahrräder stehen im Keller.", exKo:"자전거들은 지하실에 있어요."},
  {id:"v077", de:"die Nachricht", pl:"Nachrichten", ko:"소식, 메시지", ex:"Ich habe eine gute Nachricht.", exKo:"좋은 소식이 있어요."},
  {id:"v078", de:"das Gespräch", pl:"Gespräche", ko:"대화", ex:"Wir hatten ein langes Gespräch.", exKo:"우리는 긴 대화를 나눴어요."},
  {id:"v079", de:"die Einladung", pl:"Einladungen", ko:"초대(장)", ex:"Danke für die Einladung!", exKo:"초대해 줘서 고마워요!"},
  {id:"v080", de:"das Geschenk", pl:"Geschenke", ko:"선물", ex:"Das Geschenk gefällt ihr bestimmt.", exKo:"그 선물은 분명 그녀 마음에 들 거예요."},
  // ---- 형용사 ----
  {id:"v081", de:"wichtig", ko:"중요한", ex:"Das ist mir sehr wichtig.", exKo:"그건 나에게 아주 중요해요."},
  {id:"v082", de:"möglich", ko:"가능한", ex:"Ist das möglich?", exKo:"그게 가능해요?"},
  {id:"v083", de:"günstig", ko:"저렴한, 유리한", ex:"Das Hotel war ziemlich günstig.", exKo:"그 호텔은 꽤 저렴했어요."},
  {id:"v084", de:"kostenlos", ko:"무료의", ex:"Der Eintritt ist kostenlos.", exKo:"입장은 무료예요."},
  {id:"v085", de:"pünktlich", ko:"시간을 지키는", ex:"Bitte sei pünktlich!", exKo:"제시간에 와!"},
  {id:"v086", de:"zufrieden", ko:"만족한", ex:"Ich bin mit der Arbeit zufrieden.", exKo:"나는 그 일에 만족해요."},
  {id:"v087", de:"traurig", ko:"슬픈", ex:"Warum bist du so traurig?", exKo:"왜 그렇게 슬퍼해?"},
  {id:"v088", de:"glücklich", ko:"행복한", ex:"Sie sieht glücklich aus.", exKo:"그녀는 행복해 보여요."},
  {id:"v089", de:"laut", ko:"시끄러운", ex:"Die Musik ist zu laut.", exKo:"음악이 너무 시끄러워요."},
  {id:"v090", de:"leise", ko:"조용한", ex:"Sprich bitte leise!", exKo:"조용히 말해 줘!"},
  {id:"v091", de:"sauber", ko:"깨끗한", ex:"Die Küche ist jetzt sauber.", exKo:"부엌이 이제 깨끗해요."},
  {id:"v092", de:"schmutzig", ko:"더러운", ex:"Meine Schuhe sind schmutzig.", exKo:"내 신발이 더러워요."},
  {id:"v093", de:"schwierig", ko:"어려운", ex:"Die Frage ist schwierig.", exKo:"그 질문은 어려워요."},
  {id:"v094", de:"einfach", ko:"쉬운, 간단한", ex:"Das ist ganz einfach.", exKo:"그건 아주 간단해요."},
  {id:"v095", de:"fertig", ko:"다 된, 끝난", ex:"Bist du fertig?", exKo:"너 다 했어?"},
  {id:"v096", de:"kaputt", ko:"고장 난", ex:"Die Waschmaschine ist kaputt.", exKo:"세탁기가 고장 났어요."},
  {id:"v097", de:"frei", ko:"비어 있는, 자유로운", ex:"Ist dieser Platz noch frei?", exKo:"이 자리 비어 있나요?"},
  {id:"v098", de:"besetzt", ko:"사용 중인, 차 있는", ex:"Die Toilette ist besetzt.", exKo:"화장실이 사용 중이에요."},
  {id:"v099", de:"anstrengend", ko:"힘든, 고된", ex:"Der Tag war sehr anstrengend.", exKo:"오늘 하루는 아주 힘들었어요."},
  {id:"v100", de:"spannend", ko:"흥미진진한", ex:"Der Film war spannend.", exKo:"그 영화는 흥미진진했어요."},
  {id:"v101", de:"langweilig", ko:"지루한", ex:"Die Vorlesung war langweilig.", exKo:"그 강의는 지루했어요."},
  {id:"v102", de:"gefährlich", ko:"위험한", ex:"Das ist zu gefährlich.", exKo:"그건 너무 위험해요."},
  {id:"v103", de:"bequem", ko:"편안한", ex:"Der Sessel ist sehr bequem.", exKo:"그 안락의자는 아주 편해요."},
  {id:"v104", de:"eigentlich", ko:"사실은, 원래", ex:"Eigentlich wollte ich früher gehen.", exKo:"사실 나는 더 일찍 가려고 했어요."},
  // ---- 접속사 · 부사 (A2 문법 핵심) ----
  {id:"v105", de:"weil", gr:"부문장: 동사 맨 끝", ko:"~때문에", ex:"Ich bleibe zu Hause, weil ich krank bin.", exKo:"나는 아파서 집에 있어요."},
  {id:"v106", de:"dass", gr:"부문장: 동사 맨 끝", ko:"~라는 것", ex:"Ich glaube, dass er recht hat.", exKo:"나는 그가 옳다고 생각해요."},
  {id:"v107", de:"wenn", gr:"부문장: 동사 맨 끝", ko:"~할 때, ~라면", ex:"Wenn es regnet, nehme ich den Bus.", exKo:"비가 오면 나는 버스를 타요."},
  {id:"v108", de:"deshalb", gr:"뒤 문장 도치", ko:"그래서", ex:"Ich war müde, deshalb bin ich früh ins Bett gegangen.", exKo:"나는 피곤해서 일찍 잤어요."},
  {id:"v109", de:"trotzdem", gr:"뒤 문장 도치", ko:"그럼에도 불구하고", ex:"Es regnet, trotzdem gehen wir spazieren.", exKo:"비가 오지만 그래도 우리는 산책해요."},
  {id:"v110", de:"zuerst", ko:"우선, 먼저", ex:"Zuerst frühstücke ich.", exKo:"먼저 나는 아침을 먹어요."},
  {id:"v111", de:"danach", ko:"그 후에", ex:"Danach gehe ich zur Arbeit.", exKo:"그 후에 나는 일하러 가요."},
  {id:"v112", de:"plötzlich", ko:"갑자기", ex:"Plötzlich hat es geregnet.", exKo:"갑자기 비가 왔어요."},
  {id:"v113", de:"schon", ko:"이미, 벌써", ex:"Ich bin schon fertig.", exKo:"나 벌써 다 했어."},
  {id:"v114", de:"noch", ko:"아직, 더", ex:"Ich brauche noch zehn Minuten.", exKo:"10분 더 필요해요."},
  {id:"v115", de:"erst", ko:"겨우, ~이 되어서야", ex:"Er kommt erst um zehn.", exKo:"그는 10시나 되어야 와요."},
  {id:"v116", de:"bald", ko:"곧", ex:"Bis bald!", exKo:"곧 봐요!"},
  {id:"v117", de:"früher", ko:"예전에", ex:"Früher habe ich in Seoul gewohnt.", exKo:"예전에 나는 서울에 살았어요."},
  {id:"v118", de:"letzte Woche", ko:"지난주", ex:"Letzte Woche war ich krank.", exKo:"지난주에 나는 아팠어요."},
  {id:"v119", de:"nächstes Jahr", ko:"내년", ex:"Nächstes Jahr machen wir Urlaub in Korea.", exKo:"내년에 우리는 한국에서 휴가를 보내요."},
  {id:"v120", de:"zum Beispiel", ko:"예를 들면", ex:"Ich mag Obst, zum Beispiel Äpfel.", exKo:"나는 과일을 좋아해요, 예를 들면 사과요."},
];

// drills: ko(한국어 문제), de(정답), alt(허용 답안), note(한 줄 문법 설명)
const DRILLS = [
  // Perfekt (haben/sein + 과거분사)
  {id:"d001", ko:"나는 어제 피자를 먹었어요.", de:"Ich habe gestern Pizza gegessen.", note:"과거(Perfekt) = haben + 과거분사(문장 끝). essen → gegessen"},
  {id:"d002", ko:"우리는 프랑크푸르트로 이사했어요.", de:"Wir sind nach Frankfurt umgezogen.", note:"이동·변화 동사는 sein + 과거분사: sind ... umgezogen"},
  {id:"d003", ko:"그는 8시에 일어났어요.", de:"Er ist um acht Uhr aufgestanden.", note:"aufstehen은 sein을 써요: ist aufgestanden"},
  {id:"d004", ko:"너 내 메시지 받았어?", de:"Hast du meine Nachricht bekommen?", note:"be-로 시작하는 동사는 ge- 없이: bekommen"},
  {id:"d005", ko:"무슨 일이 있었어요?", de:"Was ist passiert?", note:"passieren은 sein: ist passiert"},
  {id:"d006", ko:"나는 열쇠를 잃어버렸어요.", de:"Ich habe meinen Schlüssel verloren.", note:"der Schlüssel → 목적어(Akk.)에서 meinen"},
  {id:"d007", ko:"갑자기 비가 왔어요.", de:"Plötzlich hat es geregnet.", note:"Plötzlich이 1번째 → 동사 2번째(hat), 주어 3번째(es)"},
  {id:"d008", ko:"예전에 나는 서울에 살았어요.", de:"Früher habe ich in Seoul gewohnt.", note:"Früher 도치 + Perfekt: habe ... gewohnt"},
  // Präteritum (war/hatte/konnte/musste)
  {id:"d009", ko:"지난주에 나는 아팠어요.", de:"Letzte Woche war ich krank.", note:"sein·haben의 과거는 Präteritum: war / hatte"},
  {id:"d010", ko:"나는 시간이 없었어요.", de:"Ich hatte keine Zeit.", note:"haben의 과거: hatte"},
  {id:"d011", ko:"나는 어제 올 수 없었어요.", de:"Ich konnte gestern nicht kommen.", note:"können의 과거: konnte (+ 동사원형 문미)"},
  {id:"d012", ko:"나는 일해야 했어요.", de:"Ich musste arbeiten.", note:"müssen의 과거: musste"},
  // 부문장 (weil/dass/wenn) — telc 단골
  {id:"d013", ko:"나는 아파서 집에 있어요.", de:"Ich bleibe zu Hause, weil ich krank bin.", note:"weil 부문장에서는 동사가 맨 끝으로!"},
  {id:"d014", ko:"나는 그가 옳다고 생각해요.", de:"Ich glaube, dass er recht hat.", note:"dass 부문장도 동사가 맨 끝: ... recht hat"},
  {id:"d015", ko:"비가 오면 나는 버스를 타요.", de:"Wenn es regnet, nehme ich den Bus.", note:"Wenn절이 앞에 오면 주절은 동사부터: ..., nehme ich ..."},
  {id:"d016", ko:"나는 피곤해서 일찍 잤어요.", de:"Ich war müde, deshalb bin ich früh ins Bett gegangen.", note:"deshalb 뒤에는 도치: deshalb bin ich ..."},
  {id:"d017", ko:"비가 오지만 그래도 우리는 산책해요.", de:"Es regnet, trotzdem gehen wir spazieren.", note:"trotzdem 뒤에도 도치: trotzdem gehen wir ..."},
  // Dativ 동사
  {id:"d018", ko:"프랑크푸르트가 마음에 들어요.", de:"Frankfurt gefällt mir.", alt:["Frankfurt gefällt mir gut."], note:"gefallen은 Dativ와 함께: mir (mich 아님!)"},
  {id:"d019", ko:"그 휴대폰은 내 거예요.", de:"Das Handy gehört mir.", note:"gehören + Dativ: mir"},
  {id:"d020", ko:"머리가 아파요.", de:"Ich habe Kopfschmerzen.", note:"아픔 표현: ~schmerzen haben (항상 복수)"},
  // 분리동사
  {id:"d021", ko:"내일 전화할게.", de:"Ich rufe dich morgen an.", note:"분리동사: 접두사(an)는 문장 맨 끝으로"},
  {id:"d022", ko:"버스가 곧 출발해요.", de:"Der Bus fährt gleich ab.", note:"abfahren → fährt ... ab"},
  {id:"d023", ko:"프랑크푸르트에서 갈아타셔야 해요.", de:"Sie müssen in Frankfurt umsteigen.", note:"조동사가 있으면 분리동사는 붙인 채 문미: umsteigen"},
  {id:"d024", ko:"기차역으로 데리러 갈게.", de:"Ich hole dich vom Bahnhof ab.", note:"abholen → hole ... ab. vom = von + dem"},
  {id:"d025", ko:"이 서식을 작성해 주세요.", de:"Bitte füllen Sie das Formular aus.", alt:["Füllen Sie bitte das Formular aus."], note:"존칭 명령 + 분리동사: füllen Sie ... aus"},
  // 재귀동사
  {id:"d026", ko:"주말이 기대돼요.", de:"Ich freue mich auf das Wochenende.", note:"sich freuen auf + Akkusativ = ~을 기대하다"},
  {id:"d027", ko:"우리는 7시에 만나요.", de:"Wir treffen uns um sieben.", alt:["Wir treffen uns um sieben Uhr.", "Wir treffen uns um 7 Uhr."], note:"sich treffen: wir → uns"},
  {id:"d028", ko:"오늘은 몸이 좀 나아요.", de:"Ich fühle mich heute besser.", note:"sich fühlen + 비교급 besser(gut의 비교급)"},
  // 비교급
  {id:"d029", ko:"독일어가 영어보다 어려워요.", de:"Deutsch ist schwieriger als Englisch.", note:"비교급 = 형용사 + -er + als"},
  {id:"d030", ko:"오늘이 어제보다 따뜻해요.", de:"Heute ist es wärmer als gestern.", note:"warm → wärmer (a는 움라우트로!)"},
  {id:"d031", ko:"날씨가 내일 나아질 거예요.", de:"Das Wetter wird morgen besser.", note:"gut → besser (불규칙 비교급)"},
  // 생활 실전 문장
  {id:"d032", ko:"기차가 20분 연착이에요.", de:"Der Zug hat zwanzig Minuten Verspätung.", alt:["Der Zug hat 20 Minuten Verspätung."], note:"연착 표현: Verspätung haben"},
  {id:"d033", ko:"카드로 계산해도 되나요?", de:"Kann ich mit Karte bezahlen?", note:"mit Karte / bar(현금으로) bezahlen"},
  {id:"d034", ko:"계산서 주세요!", de:"Die Rechnung, bitte!", note:"식당에서 계산할 때 그대로 쓰는 표현"},
  {id:"d035", ko:"이 자리 비어 있나요?", de:"Ist dieser Platz noch frei?", alt:["Ist der Platz noch frei?"], note:"dieser Platz(남성 주격). 대답: Ja, bitte! / Nein, besetzt."},
  {id:"d036", ko:"난방이 안 돼요.", de:"Die Heizung funktioniert nicht.", note:"고장 신고 표현: funktioniert nicht = 작동 안 함"},
  {id:"d037", ko:"그는 시험에 합격했어요.", de:"Er hat die Prüfung bestanden.", note:"bestehen(합격하다) → hat bestanden"},
  {id:"d038", ko:"월세가 너무 비싸요.", de:"Die Miete ist zu hoch.", note:"월세·가격이 '비싸다'는 teuer가 아니라 hoch"},
  {id:"d039", ko:"이 약을 하루 세 번 드세요.", de:"Nehmen Sie das Medikament dreimal täglich.", note:"존칭 명령문: Nehmen Sie ..."},
  {id:"d040", ko:"초대해 줘서 고마워요!", de:"Danke für die Einladung!", note:"danke für + Akkusativ"},
];
